version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: todoDb
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Todo_Backend/TodoListApi/Dockerfile
    ports:
      - '5000:80'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Database=todoDb;Username=your_db_user;Password=your_db_password
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Todo_Frontend/TodoListWeb/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  db-data:
